# Generated by Django 5.0.3 on 2024-03-26 16:57

import network.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_picture',
            field=models.ImageField(default='background_pictures/defaultBackground.png', upload_to=network.models.path_and_rename),
        ),
    ]
