# Generated by Django 4.2.5 on 2023-11-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='image',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
