# Generated by Django 4.2.5 on 2023-11-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auctionlisting_current_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
