# Generated by Django 4.2.5 on 2023-12-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auctionlisting_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
