# Generated by Django 4.2.5 on 2023-12-07 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auctionlisting_last_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='last_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_bid', to='auctions.bid'),
        ),
    ]
