# Generated by Django 4.2.5 on 2023-12-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auctionlisting_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
