# Generated by Django 4.2.5 on 2023-12-11 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='image_data',
        ),
    ]
