# Generated by Django 4.2.5 on 2023-12-11 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_rename_image_user_image_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image_data',
            new_name='image_blob',
        ),
    ]
