# Generated by Django 4.2.5 on 2023-12-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_rename_image_data_user_image_blob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image_blob',
            new_name='image_upload',
        ),
    ]
