# Generated by Django 4.2.5 on 2023-12-11 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_rename_image_blob_user_image_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image_upload',
            new_name='image_blob',
        ),
    ]
